<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://www.example.org/de/tu-dresden/inf/swt/2/ws2014/regtest/ns" xmlns:apachesoap="http://xml.apache.org/xml-soap2" xmlns:impl="http://www.example.org/de/tu-dresden/inf/swt/2/ws2014/regtest/ns" xmlns:intf="http://www.example.org/de/tu-dresden/inf/swt/2/ws2014/regtest/ns" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on May 20, 2008 (05:12:03 CEST)-->

   <wsdl:portType name="NoMethod">

   </wsdl:portType>

   <wsdl:binding name="NoMethodSoapBinding" type="impl:NoMethod">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http11"/>

   </wsdl:binding>

   <wsdl:service name="NoMethodService_Impl">

      <wsdl:port binding="impl:NoMethodSoapBinding" name="NoMethod">

         <wsdlsoap:address location="http://www.example.org/de/tu-dresden/inf/swt/2/ws2014/regtest/NoMethod"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
